name: firebase_services
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  logger: ^2.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  firebase_analytics: ^10.5.0
  firebase_auth: ^4.10.0
  firebase_ui_auth: ^1.8.0
  cloud_firestore: ^4.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
